# FROM node:18-alpine as build

# WORKDIR /usr/src/app

# COPY packages*.json .

# RUN npm install

# COPY . .

# RUN npm run build


#####################################

FROM node:18 as prod

ARG NODE_ENV=production

# ENV NODE_ENV=${NODE_ENV}
ENV PORT=9000
ENV MONGO_URI =mongodb://admin:admin@localhost:27017/
ENV JWT_SECRET ="Some_secret_needs_to_be_decided"
ENV STRIPE_SECRET_KEY="pk_test_51OgSk1SHYwCJi5OxJSX1qFYlZm64WYPBs8NA0Nq37iiGBvOJDYMBVVag2NkPbJvPX1RUTd5lqqCuVHwoN8bcCztY00C3WNmTkp"

WORKDIR  /usr/src/app

# COPY package*.json .

# RUN npm install --only=production

RUN echo ${pwd}  > /tmp/DIlog.txt
RUN ls -a >> /tmp/DIlog.txt

COPY  . /usr/src/app/

RUN npm install 


# RUN npm run dev


CMD ["node", "dist/src/app.js"]

